apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  POSTGRES_USER: devops
  POSTGRES_PASSWORD: devops
  POSTGRES_DB: app_db
  DATABASE_URL: postgres://devops:devops@postgres:5432/app_db
