apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-playground.frontendServiceName" . }}
  labels:
    {{- include "devops-playground.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    {{- include "devops-playground.frontendLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
